version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: jobhunter_api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    env_file:
      - api/.env
    ports:
      - "5046:5046"
    volumes:
      - ./api:/app  
    depends_on:
      - postgres
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    volumes:
      - ./admin:/app
    ports:
      - "3003:3003"
    depends_on:
      - api
volumes:
  postgres_data:

